apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dev-e2e-tests-
  namespace: devnet-issue-727
spec:
  entrypoint: test-e2e
  serviceAccountName: e2e-tests
  templates:
    - name: test-e2e
      container:
        image: ghcr.io/pokt-network/pocket-v1:sha-35eb743feb0e74e2fb39399abc6efdc0155840de-dev
        imagePullPolicy: IfNotPresent
        command: [make, test_e2e]
        env:
          - name: RPC_HOST
            value: pocket-validators
        resources:
          limits:
            cpu: "4"
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
